### ISSUE TITLE
Broken link in README to "Azure Container Apps code-to-cloud quickstart"

### ISSUE THREAD

**Issue by clarenceb** [Azure-Samples/containerapps-albumapi-javascript#1]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce

Click on the link [Azure Container Apps code-to-cloud quickstart](https://github.com/Azure-Samples/containerapps-albumapi-javascript/blob/main) => 404 not found

### Any log messages given by the failure

n/a

### Expected/desired behavior

Should take me to the correct destination page.

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

Windows 11

### Versions

n/a

### Mention any other details that might be useful

n/a

**Comment by kendallroden** [comment]
The doc doesn't exit yet @clarenceb
